[project]
name = "phone-detection-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "PyQt5-Qt5==5.15.2",
    "PyQt5_sip==12.17.0",
    "PyQt5==5.15.11",
    "mss>=10.0.0",
    "opencv-python>=4.11.0.86",
    "psutil>=7.0.0",
    "pyarmor>=9.1.5",
    "pywin32>=310",
    "scikit-image>=0.25.2",
    "pyautogui>=0.9.54",
    "numpy>=2.1.0",
    "onnx>=1.22.0",
    "onnx-simplifier>=0.5.0",
    "onnxruntime>=1.28.0",
    "onnxslim>=0.1.94",
    "requests>=2.32.3",
    "scipy>=1.15.2",
    "fastapi>=0.115.0",
    "uvicorn>=0.30.0",
    "sqlalchemy>=2.0.30",
    "jinja2>=3.1.4",
    "python-multipart>=0.0.12",
    "aiofiles>=24.1.0",
    "ultralytics>=8.3.0",
    "torch>=2.4.0",
    "torchvision>=0.19.0",
]
